### ISSUE TITLE
Stop while mip running

### ISSUE THREAD

**Issue by gh1134** [WowWeeLabs/MiP-BLE-Protocol#6]
I run into a new issue here:

I first make the mip move forward, and the mip should stop when it sense an obstacle in the front.
However, I found out that when the mip is moving forward the radar won't work until it finish running forward. 

During the mip moving forward, I can't get the radar value until the previous command finish executing. In other word, while it's running it won't sense anything until the forward command is finished. 

Is there a way to work this around? I'm using a thread for radar and a thread for moving forward.

**Comment by hongkongkiwi** [comment]
At this stage, we don't plan to do any firmware updates on MiP because the firmware update code can cause some non-technical customers' MiPs to stop working if they stop it half way through. So any bugs unless they are really major are not in our roadmap for fixing.

We might release the firmware updating capability for SDK users though but that wouldn't be for a few months.

However, what I would like to know is does this also happen with different movement commands? As you can see in the protocol there are different types of movement commands. Does the problem happen with all of them?

**Comment by gh1134** [comment]
Hi Andy, 
So far I've tried all commands to move forward. Since right and left happen very fast, probably I didn't notice the issue. 

Do you have any suggestion if I want to sense an object and stop before it?

Thank you 
Date: Tue, 27 Jan 2015 18:56:31 -0800

**Comment by hongkongkiwi** [comment]
Currently, we don't plan to issue a firmware update for this issue.

**Comment by adamgreen** [comment]
@gh1134 I have found that if I send the **Continuous Drive (0x78)** Command, then I still receive the radar mode notifications while the MiP is moving.  Can you switch your motion thread to use that command instead?
